# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75002ef138a98a0da027c1575b4ad75e01f0c3b4eb70965f5a36f324280e149720892a50a14b3ec7a989d623a871970faf373333858a68eaa106c61b3d8875ea

test:
  secret_key_base: bcbaef8563811a918194cb06eb5d26a8c8086e2dcb8fd61803733fe315d90db3bfd6e4f3a9779f5089e01eac99ab2d17214522d6d5b3255a992011af5c71cd55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
